config/routes.rb
Rails.application.routes.draw do
  #get 'relationships/followings'
  #get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about"
  get "/search" => "searches#search"

  resources :users, only: [:index,:show,:edit,:update] do
   
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
  # belongs_to :follower, class_name: "User" #フォローするユーザー
  # belongs_to :followed, class_name: "User" #フォローされるユーザー
  
  # validates :user_id, presence: true
  # validates :follow_id, presence: true

  #validates :follower_id, uniqueness: { scope: :followed_id }
#参考記事　https://tech-essentials.work/course_outputs/165
# この記述でfollower_idとfollowed_idの組をuniqueにした。１通りのみ許可のバリデーション。
# uniquenessはRails Validationヘルパーの一つで属性の値が一意（unique）であり重複していないことを検証する。
# （属性について同じ値のレコードがモデルにあるかをクエリを走らせ確認する）
# scopeオプションは他のカラムに一意性制約を求めることが出来る。
# 今回のケースだと、ひとつの":follower_id"シンボルに紐づくscope先の"followed_id"カラムのレコードに対しuniquenessを実行している。

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    user = User.find(params[:user_id])
    current_user.follow(user)
    redirect_to request.referer
  end

  def destroy
    user = User.find(params[:user_id])
    current_user.unfollow(user)
    redirect_to request.referer
  end

  #フォロー一覧
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  #フォロワー一覧
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

  #フォローする
  # def create
  #   current_user.follow(params[:user_id])
  #   redirect_to request.referer
  # end

  # #フォロー外す
  # def destroy
  #   current_user.unfollow(params[:user_id])
  #   redirect_to request.referer
  # end




#   private

#   def relationships_params
#     params.require(:user).permit(:follower_id, :followed_id)
#   end


# end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_btn.html.erb
<% if current_user != user%>
  <% if current_user.following?(user) %>
    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
  <% end %>
<% end %>

app/views/relationships/followers.html.erb
<h1>Follower Users</h1>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>


<!--<table class='table'>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>image</th>-->
<!--      <th>name</th>-->
<!--      <th colspan="3"></th>-->
<!--      <th colspan="3"></th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->
<!--  <tbody>-->
<!--    <%# @users.each do |user| %>-->
<!--    <tr>-->
<!--      <td><%#= image_tag user.get_profile_image(50,50) %></td>-->
<!--      <td><%#= user.name %></td>-->
<!--      <td>フォロー数：<%#= user.followings.count %></td>-->
<!--      <td>フォロワー数：<%#= user.followers.count %></td>-->
<!--      <td><%#= link_to "Show", user_path(user.id) %></td>-->
<!--    </tr>-->
<!--    <%# end %>-->
<!--  </tbody>-->
<!--</table>-->

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>