config/routes.rb
Rails.application.routes.draw do
  #get 'relationships/followings'
  #get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about"
  get "/search" => "searches#search"

  resources :users, only: [:index,:show,:edit,:update] do
   
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  belongs_to :user
  validates :title,presence:true
  validates :body, presence:true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  #search機能のメソッド
  def self.looks(searches,words)
    if searches == "forward_match"
      @books = Book.where("title LIKE ?", "#{words}%")
    elsif searches == "backward_match"
      @books = Book.where("title LIKE ?", "%#{words}")
    elsif searches == "perfect_match"
      @books = Book.where("title LIKE ?", "#{words}")
    elsif searches == "partial_match"
      @books = Book.where("title LIKE ?", "%#{words}%")
    end
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :authenticate_user!, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
     @user = @book.user
     @books = Book.new#renderへの値
     @book_comment = BookComment.new#コメントを投稿するためのインスタンス変数
  end

  def index
    @books = Book.all
    @book = Book.new#renderへの値
    
    @q = Book.ransack(params[:q])
    @books = @q.result(distinct: true)
    #@books = Book.all.order(created_at: :desc)
   
  end


  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :star, :content, :category)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
    redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
 <% if book.errors.any? %>
      <%= book.errors.count %>error prohibited this obj from being saved:
      <ul>
        <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>



<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.label :category %>
    <%= f.text_area :category, class: 'form-control book_category' %>
  </div>
  <div class="field">
    <div class="form-group row" id="star", class: "form-control" >
      <%= f.hidden_field :star, id: :review_star %>
    </div>
  </div>

   <!-- 評価javascript -->
  <script>
  $(document).on('turbolinks:load', function() {
    $('#star').empty();
    $('#star').raty({
      size     : 36,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn : '<%= asset_path('star-on.png') %>',
      scoreName: 'book[star]',
      half: false,
    });
  })
  </script>
  
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

 

app/views/books/_index.html.erb
<%= sort_link(q, :created_at, "新しい順", hide_indicator: true ) %> |  
<%= sort_link(q, :star, "評価の高い順", hide_indicator: true) %>

<table class='table table-hover table-inverse'>
  <thead class="thead-light">
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image(50,50) %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td><%= sort_link(q, :category_eq, book.category,book, hide_indicator: true) %></td>
        <%#= link_to book.category,book, class: "book_#{book.id}" %>
        <td id="favorite_buttons_<%= book.id %>">
　　    　<%= render "favorites/favorites", book: book %>
　　    </td>
        <td id="comment_counter">
　　      <%= render "book_comments/counter", book: book %>
        </td>
        <!--ここから下追記-->
        <td>
          <div id="star-rate<%= book.id%>"></div>
          <script>
          $(document).on('turbolinks:load', function() {
            $('#star-rate<%= book.id %>').empty();
            $('#star-rate<%= book.id%>').raty({
              size      : 36,
              starOff   : '<%= asset_path('star-off.png') %>',
              starOn    : '<%= asset_path('star-on.png') %>',
              half      : false,
              readOnly: true,
              score: <%= book.star %>,
            });
          });
          </script>
          </div>
        </td>
        <!--ここまで-->
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
      <%= @book.errors.count %>error prohibited this obj from being saved:
      <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>

<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		
  		<!--この下にあえて記述-->
  		
      <%= form_with model:@book, local: true do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control book_title' %>
        </div>
        <div class="form-group">
          <%= f.label :opinion %>
          <%= f.text_area :body, class: 'form-control book_body' %>
        </div>
        <div class="form-group">
          <%= f.label :category %>
          <%= f.text_area :category, class: 'form-control book_category' %>
        </div>
        <div class="form-group">
          <%= f.submit class: 'btn btn-success' %>
        </div>
        
        <div class="field">
          <div class="form-group row" id="star">
            <%= f.hidden_field :star, id: :review_star %>
          </div>
        </div>
      
         <!-- 評価javascript -->
        <script>
        $('#star').raty({
          size     : 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          scoreName: 'book[star]',
          half: false,
          readOnly: true,
          score: <%= @book.star %>,
        });
        </script>
      <% end %>

  		<!--ここまで。元々は下のrenderのみ-->
  		<%#= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', {books: @books, q: @q} %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>

    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user  %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @books %>
    </div>

    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image(100,100) %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td><%= @book.category %></td>
          
          <!--ここから下追記-->
          <td>
            <div id="star-rate<%= @book.id%>"></div>
            <script>
            $(document).on('turbolinks:load', function() {
              $('#star-rate<%= @book.id %>').empty();
              $('#star-rate<%= @book.id %>').raty({
                size      : 36,
                starOff   : '<%= asset_path('star-off.png') %>',
                starOn    : '<%= asset_path('star-on.png') %>',
                half      : false,
                readOnly: true,
                score: <%= @book.star %>,
              });
            });
            </script>
          </td>
          <!--ここまで-->

          <% if @user == current_user %>
          <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
          <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>

          <td id="favorite_buttons_<%= @book.id %>">
　　    　<%= render "favorites/favorites", book: @book %>
　　    </td>
          <!--<td>-->
          <!-- <%##= link_to book_favorites_path(@book), method: :delete do %>-->
          <!--    ♥<%#= @book.favorites.count %>-->
          <!--  <%# end %>-->
          <!--<%# else %>-->
          <!--  <%#= link_to book_favorites_path(@book), method: :post do %>-->
          <!--    ♡<%#= @book.favorites.count %>-->
          <!--  <%# end %>-->
          <!--<%# end %>-->
          <!--</td>-->
          <td id="comment_counter">
　　        <%= render "book_comments/counter", book: @book %>
          </td>
        </tr>
      </table>

      <div id="comments">
　　    <%= render "book_comments/comments", book: @book, book_comment: @book_comment %>
　　  </div>
      <!--<%# @book.book_comments.each do |book_comment| %>-->
      <!--<p>-->
      <!--  <%#= image_tag book_comment.user.get_profile_image(50,50) %>-->
      <!--  <%#= book_comment.user.name %>-->
      <!--  <%#= book_comment.created_at.strftime('%Y/%m/%d') %>-->
      <!--  <%#= book_comment.comment %>-->
      <!--  <%# if book_comment.user == current_user %>-->
      <!--    <%#= link_to book_book_comment_path(book_comment.book, book_comment), class: "btn btn-danger", method: :delete do %>-->
      <!--    <i class="button"></i>-->
      <!--    Destroy-->
      <!--    <%# end %>-->
      <!--  <%# end %>-->
      <!--<%# end %>-->
      <!--</p>-->
      <!--<p>-->
      <!--  <%#= form_with model: [@book, @book_comment] do |f| %>-->
      <!--  <%#= f.text_area :comment, rows: '5', placeholder: "コメントをここに", class: "w-100" %><!--←class横幅の指定-->
      <!--  <%#= f.submit "送信する" %>-->
      <!--  <%# end %>-->
      <!--</p>-->

    </div>

  </div>
</div>